from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

import cv2
import numpy as np

from mosaic_collage_converter import load_tile_library, render_mosaic


def read_image(path: Path) -> np.ndarray:
    image = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if image is None:
        raise FileNotFoundError(f"Cannot read image: {path}")
    return image


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def pixel_positions(pixel_count: int, pixel_seed: int) -> list[int]:
    positions = list(range(pixel_count))
    rng = random.Random(pixel_seed)
    rng.shuffle(positions)
    return positions


def mrt_coords_to_symbol(coords: list[int], m: int, n: int, perm_seed: int) -> int:
    """Reverse the seeded MRT coordinate mapping."""
    total_symbols = m**n
    rng = random.Random(perm_seed)
    permutation = list(range(total_symbols))
    rng.shuffle(permutation)
    inverse = {value: index for index, value in enumerate(permutation)}

    value = 0
    for coord in coords[:n]:
        value = value * m + int(coord)
    return int(inverse.get(value, 0))


def extract_symbols(stego_bgr: np.ndarray, key: dict) -> list[int]:
    """Extract tile index symbols from the stego image Y channel."""
    m = int(key["M"])
    n = int(key["N"])
    symbol_count = int(key["symbol_count"])
    perm_seed = int(key["perm_seed"])
    pixel_seed = int(key["pixel_seed"])

    ycrcb = cv2.cvtColor(stego_bgr, cv2.COLOR_BGR2YCrCb)
    y_channel = ycrcb[:, :, 0]
    required_pixels = symbol_count * n
    if required_pixels > y_channel.size:
        raise ValueError(f"Stego image is too small: need {required_pixels}, got {y_channel.size}.")

    positions = pixel_positions(y_channel.size, pixel_seed)
    symbols: list[int] = []

    for symbol_index in range(symbol_count):
        coords: list[int] = []
        for offset in range(n):
            pos = positions[symbol_index * n + offset]
            coords.append(int(y_channel.flat[pos]) % m)
        symbols.append(mrt_coords_to_symbol(coords, m, n, perm_seed))

    return symbols


def decode(stego_path: Path, key_path: Path, tile_folder: Path, out_path: Path) -> None:
    key = read_json(key_path)
    stego = read_image(stego_path)

    symbols = extract_symbols(stego, key)
    rows = int(key["index_rows"])
    cols = int(key["index_cols"])
    block_size = int(key["block_size_pixels"])
    tile_seed = key.get("tile_seed")

    tiles, _ = load_tile_library(tile_folder, block_size, seed=tile_seed)
    index_map = np.array(symbols, dtype=np.int32).reshape(rows, cols) % len(tiles)
    mosaic = render_mosaic(index_map, tiles, block_size)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(out_path), mosaic)
    print("Done.")
    print(f"Decoded mosaic image: {out_path}")
    print(f"Extracted symbols: {len(symbols)}")
    print(f"Block size: {block_size}x{block_size} pixels")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Decode a stego image into a mosaic image using MRT-SIE key and tile library.")
    parser.add_argument("--stego", required=True, help="Stego image path.")
    parser.add_argument("--key", required=True, help="Embedding key JSON generated by mrt_sie_embedder.py.")
    parser.add_argument("--tiles", required=True, help="Folder containing tile images.")
    parser.add_argument("--out", default="outputs/decoded/decoded_mosaic.png", help="Output decoded mosaic image path.")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    decode(Path(args.stego), Path(args.key), Path(args.tiles), Path(args.out))


if __name__ == "__main__":
    main()

